services:
  mongodb:
    image: mongo:latest
    container_name: desafio-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - desfio_mongo_data:/data/db
volumes:
  desfio_mongo_data: